### PR TITLE
Rudimentary support for config file

### PR DESCRIPTION
**Pull request by Kixunil**
This adds very rough support for configuration file in toml format in
order to prevent editing the code in order to configure the server.

### CODE REVIEW

**Comment by nickfarrow** [comment]
I am split on this one.

On one hand I understand that isn't so nice to have to directly edit a python file, but yet it is still rather simplistic and straightforward, with little code. I am am wondering if using something more powerful is entirely necessary. 

I have not seen `.toml` before. Perhaps audience is something to consider here, what are ppl more comfortable editing?

Interested to hear your/others thoughts.

Also, what are lines 4-15 for?
https://github.com/nickfarrow/BTCPyment/pull/4/commits/a49859ebc5bfd66ba05be7cf0c3ef8b7c9e9d257#diff-117426151e93a626f8b46bfdb3a95b3f4a62e5f4dd6e65975a7c50759bf04482R4-R15

**Comment by Kixunil** [comment]
The main reason I changed it is to enable integration into my repository when it's ready. Not editing Python files is a requirement. Further tests are simpler if only required fields are filled.

This is meant as initial step towards something nicer, not a final design. We can improve it over time.

>  I guess the cat <<EOF be done into a python file?

Not really, the repository currently doesn't support stable Python API for such configuration, only shell API. It will come at some point in the future. I could have implemented it by re-writing that logic but I prefer not to put unstable/unofficial APIs to other projects. (And I know for a fact that it will change when I refactor it in the future.)

>I have not seen `.toml` before. Perhaps audience is something to consider here, what are ppl more comfortable editing?

It was designed for config files like this one and does that job really well. It's going to be used in Python build systems and it's very popular in Rust as well. As you can see the syntax is mostly very simple and we don't need to use advanced features. Availability of the library is also great.

>Also, what are lines 4-15 for?

Basic future-proofing. It specifies `--conf` argument that can switch config file path if present. This was useful to me when manual testing (was copying whole directory from another VM) and it will be required for integration so better start with something.

Yes, the architecture is not great but it can be improved over time.

**Comment by nickfarrow** [comment]
You're right, config changes have been a growing pain and I do like the simplicity. What do you think about a slightly trimmed down version, with my intention to add complete CLI functionality in a further PR/commit (with --config flag)?

I did semi-restart with your changes, I did a
```
git mv config.py config.toml
```
then in a later commit added the new `config.py`. I'm thinking this would carry over a user's config, though it would need reformatting. But I haven't tested.

Attempt branch: https://github.com/nickfarrow/SatSale/commit/5aed283938976c03ddc4a8592b67932a4668bb10 (could push to yours)

(Currently there's a bug in with how clightning args are loaded so that needs to be fixed for this above to work perfectly)

**Comment by Kixunil** [comment]
From my experience it's really annoying not being able to set specific configuration file. I think that should definitely be supported. It's just 12 lines of code - not complex at all.

**Comment by nickfarrow** [comment]
I agree, I would like to fix running in production via `gunicorn -w 1 satsale:app` (more sys argv), will leave as is until I build a fully fleshed out cli.

**Pull request merged**
